version: '3.8'

services:
  github-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-bot
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONUNBUFFERED=1
    working_dir: /app
    # Uncomment the following line if you want to run in development mode with auto-reload
    # command: sh -c "pip install watchdog && watchmedo auto-restart --recursive --pattern="*.py" -- python main.py"

# Create a .env file in the same directory with your actual tokens:
# SLACK_BOT_TOKEN=xoxb-your-token
# SLACK_APP_TOKEN=xapp-your-token
# GITHUB_TOKEN=ghp_your_token
# GITHUB_REPO=owner/repo
# GEMINI_API_KEY=your-gemini-api-key
